# Generated by Django 5.1.6 on 2025-03-04 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beat',
            name='file',
        ),
        migrations.AddField(
            model_name='beat',
            name='file_url',
            field=models.URLField(default='N?A'),
        ),
    ]
