# Generated by Django 5.1.6 on 2025-03-04 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_beat_file_beat_file_url'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='beat',
            unique_together={('producer', 'title', 'file_url')},
        ),
    ]
